### ISSUE TITLE
How to permanently disable SPF?

### ISSUE THREAD

**Issue by Piter432** [YePpHa/YouTubeCenter#1167]
Hello.

I have little problem with one of YouTube's functions. I have the newest developer version of YouTube Center as script version for Greasemonkey for Firefox. In the YouTube Center options I already disabled SPF, but it doesn't work sometimes. Is there any way to permanently disable the SPF function on YouTube?

**Comment by eladkarako** [comment]
You can also:
- Install [uBlock-origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm)
- Add a _[blocking rule](https://adblockplus.org/filters#basic)_: `spf.js` .
- YouTube will then fallback to a normal browsing experience.

<sub>Source: [Disable YouTube SPF](http://icompile.eladkarako.com/disable-youtube-spf/)</sub>

**Comment by Djfe** [comment]
you can disable spf in YouTubeCenter itself instead, you don't need an extra addon
but it would (have) be(en) nice if YouTubeCenter would support spf natively (I don't know whether it works right now, or not, I haven't used YouTubeCenter in a while, because it got broken)
and that's what this bug report is about
