### ISSUE TITLE
Creator Studio page & YTC  issue.

### ISSUE THREAD

**Issue by Lebon14** [YePpHa/YouTubeCenter#1362]
Hi there. I'm having an issue with the Creator Stusio page. See the image below, it will describe better than I can:
![yt-cstud](https://cloud.githubusercontent.com/assets/5299469/5690412/a06693fa-9855-11e4-8e8e-6fae83546414.png)
The issue is indeed with Youtube Center. I desactivated the plugin in firefox and the page loads correctly. I also tried removing the black theme I have and does not fix the issue. Only desactivating YTC does.

Thanks!

**Comment by ErdeFB** [comment]
Has this always happened or just started to occur recently?
Do you have any other add-ons? If yes, did you try to disable them as well before disabling YTC?
What browser? What YTC version?

In future, lease include more information in your issue reports as it makes it easier and faster for others to help you. Thanks.

**Comment by Lebon14** [comment]
It always occured.
I have many other addons and no, I have not tried to disabled them before YTC. I will try that in a minute.
Browser: Firefox 34.0.5
YTC Version: 2.1.7 (Script ver. - not the addon)

**Comment by ErdeFB** [comment]
Try the developer version from here:
https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

**Comment by Lebon14** [comment]
It fixed it. I imaginbe that it'll be fixed in the next stable version.

**Comment by mpred04** [comment]
Afraid it's occurring for me as well... I have the addon on the newest version of Firefox (36.0)
and YTC is the cause of it (I've tried to disable all of the other addons, and the error was still there)

**Comment by mpred04** [comment]
Afraid that after more than a year it's occurring for me as well... I have the newest dev version of the addon on the newest released Firefox (45.0.1)
and YTC is the cause of it (I've tried to disable all of the other addons, and the error was still there)

seems like the left Creator Studio menu is pushed a bit too far to the right and it takes the place of the main section, whch because of it moves down
Wish I'd know how to fix it myself
