### ISSUE TITLE
"Like/Dislike Button" options not work for comment likes/dislikes, "Disliked button hover" bugged

### ISSUE THREAD

**Issue by ReporterX** [YePpHa/YouTubeCenter#1371]
First, none of the settings under "Like/Dislike Button" have any effect on comment likes/dislikes.

Second, "Disliked button hover color" is bugged. It does not work.

Thank you.

Firefox 34.0.5
YTC Dev Build 461

**Comment by YePpHa** [comment]
The like/dislike button feature is currently only available for the video and I have not anything planned to extend compatibility to the comments. However, if you would like that feature then create a new issue where it's suggested.

The disliked button hover color is currently bugged, because I forgot to add an `s`.
