### ISSUE TITLE
Dock the player ontop like youtube mobile apps

### ISSUE THREAD

**Issue by alike03** [YePpHa/YouTubeCenter#1372]
It would be cool if we could be able to dock the player on top so if we scroll down to the comment section still be able to see the video. Like the youtube mobile apps.
To turn it on/off a button next to light on/off button would be an option

Example pic where you can still see the video while you're looking at the comments

![player-example](https://cloud.githubusercontent.com/assets/8145921/5714113/8247f974-9ac4-11e4-8933-9c61ee462b55.jpg)

**Comment by ErdeFB** [comment]
I would definitely use this. Please consider implementing this if it is feasible.

**Comment by Eisys** [comment]
My YT player is as big as it can be(Still hoping for @YePpHa to implement the ability to hide the header and make player even bigger..) So I wouldnt find much use out of this but it would be an amazing feature! And I think it is possible because I remember an addon or extension actually doing this.. That was a while ago though..

**Comment by Yonezpt** [comment]
@Eisys It was Youtube Options, aka SPOI. This feature is very feasible, in fact I have coded it myself in my own little hacky script, although a bit differently. It will surely be a useful option for heavy comment readers.

**Comment by Yung1683** [comment]
Please do not email me again I no longer need that thanks and regards !

yhyung

On 14 Jan 2015 02:04, Particle <notifications@github.com> wrote:
@Eisys It was Youtube Options, aka SPOI. This feature is very feasible, in fact I have coded it myself in my own little hacky script, although a bit differently. It will surely be a useful option for heavy comment readers.

---

**Comment by ErdeFB** [comment]
@Yung1683 How abut you learn how to use GitHub and unwatch this repository so you won't receive any more email notifications instead of spamming every single person's email address who watch this repo? Over 190 people received your grand show of ineptitude four times.

**Comment by Yonezpt** [comment]
@Yung1683 This is happening  because you are probably "watching" this repository:



>Watching notifications are those in which you are are actively watching a repository, but aren't necessarily participating. You will automatically receive these notifications for:

>    Opened issues and their comments
>    Opened pull requests and their comments
>    Comments on any commits
>    Published releases

https://help.github.com/articles/about-notifications/

To stop receiving further notifications from issues that you did not commented on you can follow this guide here that will help you with what you want: https://help.github.com/articles/unwatching-repositories/

**Comment by Yung1683** [comment]
I no longer need receive any more email again thanks !

yhyung

On 14 Jan 2015 19:09, Particle <notifications@github.com> wrote:
@Yung1683 This is happening  because you are probably "watching" this repository:



>Watching notifications are those in which you are are actively watching a repository, but aren't necessarily participating. You will automatically receive these notifications for:

>    Opened issues and their comments
>    Opened pull requests and their comments
>    Comments on any commits
>    Published releases

https://help.github.com/articles/about-notifications/

To stop receiving further notifications from issues that you did not commented on you can follow this guide here that will help you with what you want: https://help.github.com/articles/unwatching-repositories/

---

**Comment by KDsMax** [comment]
When using player docking it scrolls down a bit, and goes top of the playlist etc. It should not scroll down.

**Comment by YePpHa** [comment]
This has been implemented in the latest dev version.
