### ISSUE TITLE
Double Reapeat Playlist Button

### ISSUE THREAD

**Issue by F43nd1r** [YePpHa/YouTubeCenter#1377]
There is a second reapeat playlist button with hint: "undefinded" in playlist window.

![unbenannt](https://cloud.githubusercontent.com/assets/10252708/5785893/25e5af2a-9ddd-11e4-95c2-d05bd767131b.PNG)

This is my first bug report here, so if something is missing, just ask!
I don't know if this is settings specific, but it appears in both stable and developer build.

**Comment by endymion0000** [comment]
I see the third button as well now, but mine says Autoplay, so maybe Google finally realized the error of their ways in removing autoplay before.

**Comment by Seiryuu-sama** [comment]
The 2nd button doesn't exist when YC is disabled. Toggling it doesn't seem to do anything either.

**Comment by YePpHa** [comment]
The first auto-play button is for repeating the playlist not preventing auto-play of the next video in the playlist. However, the last button that @F43nd1r made a screenshot of is supposed to prevent the auto-play of the next video. This has now been fixed in the latest developer version.

@F43nd1r If you're still experiencing the `undefined` tooltip then report it again.
