### ISSUE TITLE
Once again, no thumbnail animation, no likes/dislikes on it...

### ISSUE THREAD

**Issue by campaignsong** [YePpHa/YouTubeCenter#1382]
What I did was remove it from the Firefox add-ons page, download the yeppha.github.io
on my desktop and drag it on the Firefox icon just like last time.

I checked some random video page for the animation, likes, dislikes and frame rate and
sadly, nothing, just a boring static one.

What did I do wrong this time?

Please help!

**Comment by Yonezpt** [comment]
If you haven't used the version 2.1.7 yet then you can download it from here: https://github.com/YePpHa/YouTubeCenter/wiki

Do not choose the link in front of <b>AMO</b> because it leads to an outdated version.

If you already tried the version 2.1.7 then try the latest developer version which can be found here: https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

I have tested with the developer version 461 just now and the thumbnail animation, likes/dislikes and quality all displayed correctly.

**Comment by Djfe** [comment]
I don't see the watch later button when I hover over thumbnails on the my subscribtions list
on the default page everythign works fine -> the button is visible

**Comment by Djfe** [comment]
actually there is no difference
the issue is that the hovering function doesn't work anymore
->it only works to set it to show always

I switched the settings but they only took effect after I reloaded the page which elad to a false conclusion on my site -> it happens on all sites: hovering doesn't work

**Comment by campaignsong** [comment]
I have used the dev version as suggested and it now works. Thank you very much!

I NEED my thumbnail animation!

**Comment by YePpHa** [comment]
@Djfe create a new issue for the hover issue as it's not completely the same as the one @campaignsong reported. Anyway, I can confirm that the issue you're having with i.e. 'watch later' doesn't work when it's not set to `Always`.
