### ISSUE TITLE
Google Disables Extension.

### ISSUE THREAD

**Issue by animatorwannabe** [YePpHa/YouTubeCenter#1417]
Hello, first off, love this extension. 
It's helped maintain my youtube account more than you. And I enjoyed using this extension so much that I would reinstall it EVERY TIME google disabled it. Which brings me to my point.
Every time I would install it, and would close google or turn off my computer the extension is disabled by the browser. It doesn't give me any choice in the matter it just turns off and I have no choice but to reinstall it since I would have to delete it first. Please, is there any way, or any other extension to stop this madness. It's driving me nuts. It's not just you guys either. It's almost all 3rd party extenstions that are not coming from the google extension website directly. Thank you for your help. I hope whatever issues you hare having with google gets fixed soon, since that message has been there for the year that I've been using it.

**Comment by Zarggg** [comment]
Google Chrome will disable *all* extensions that are not present in the Chrome Web Store. The only ways to resolve this are to install the JavaScript version of the extension (in conjunction with Tampermonkey), to install the extension unpacked in Developer Mode, or for Google to accept the extension on the Web Store, which is out of the author's control.

**Comment by Saren-Arterius** [comment]
That's why I don't use Chrome. I have recommended YTC to my friend who are using Chrome and get pissed off because of the same problem. After that he switched to Firefox, problem solved.

**Comment by RedDeadElite** [comment]
Here's a screenshot I took from the Google forums. I haven't tried any of this though. Might it help you?
![google chrome](https://cloud.githubusercontent.com/assets/10464602/5986566/93bf1fc8-a8c2-11e4-97b8-223fcbc65c75.png)
Just so you know, none of this is official. It was posted by a user there and voted best answer, so I saved it in case it might become relevant.

**Comment by Saren-Arterius** [comment]
This is useful while this is BS too. Anyway, thanks.

**Comment by Colbywolf** [comment]
I'll devil's advocate for a moment, Saren-Arterius.

Imagine the scenario:  You're on the hunt for an extension that does... well, a specific something.  You find one that claims to do it.  So, you install it.  Of course, you didn't realize that it also did things like... I dunno, send your credit card info to someone, or install sneaky spyware or trojans or something.  The type of bad something that would make someone uninstall instantly.  but you don't know any of that.  Someone else found that out, reported it, and chrome said "oh heck no" and yanked it out of the store.  Which is good because no one else falls for it.  And they auto disable it for everyone who's using it because, well, yikes, that's your creditcard info and that's not even a LITTLE okay.  

Now, that means that some extensions--like youtube center--get caught in the blast radius...  but it keeps the evil extensions out of the store...  is it the best plan?  Maybe not...  but it's the safest for the users, anyway. After all, if something's been removed from the store, it's probably for a reason...  no longer supported, or doesn't do as it claims, or has very shady business practices, etc.    Or in the case of YTC, probably does something they don't want easily available.

Which is all to say:  it's annoying, but it's not something they're doing just to mess with your youtubery. :)

**Comment by Saren-Arterius** [comment]
Yeah, Google is getting evil.

**Comment by Pontiac76** [comment]
I don't see how protecting people is 'evil'?  That'd be like saying
Symantec or Trend Micro are evil from protecting you from viruses with
their anti-virus software.

**Comment by Saren-Arterius** [comment]
Well, protecting people from virus or malware is certainly not evil, but preventing people from using YTC does. YTC is not malware, it's just a kind of plugin which Google don't want you to use it, then why should it get banned? 

It's just like all cracked programs and keygen, the AV said it's a virus or something else and notify the user, however the virus type displays "hacktool". Obviously it's not a virus, then why is it treated like a virus? Because the company don't want you to know its existence/use it. Simple enough.

**Comment by Colbywolf** [comment]
Okay, in regards to the cracked programs and keygen, let me explain something...  a cracked program is a program file that has been altered to circumvent part of it's code.  From a heuristic standpoint, there's not much difference between a game cracked to not 'call home' and check it's DRM, and a program that is 'infected' to, say, display a message telling you your computer is infected with a virus that you need to pay 30 bucks to get rid of.  

Your AV isn't trying to get on you for hacking a program--honestly, in a lot of cases, I've noticed that some of my 'false positives' in my cracked files come up as clean a few cycles later, suggesting that the AV company said "whoops, this isn't a virus." and 'fixed the problem.

Now, in regards to YTC ...  it's not malware, but it does change a lot about how people use youtube.  Including helping users to specifically skip and circumvent the ads that give youtube revenue...  as well as allowing you to do things like circumvent the methods youtube installs to throttle bandwidth (that is to say...  YTC lets you predownload everything rather then only a certain amount.)  among otherthings.  It is totally reasonable that Google feel a bit uneasy about YTC, and it wouldn't surprise me if I found out that the YTC dudes were working with google to find out what they'd need to change to make YTC 'okay' to be on the store.

**Comment by ErdeFB** [comment]
I appreciate the sentiment, but this is an issue tracker and not a discussion forum. Please keep that in mind.

**Comment by animatorwannabe** [comment]
Thanks everyone I appreciate it. I hate that my favorite browser is giving me such a hassle. But at least there are ways around it. Thank you again for taking the time out to reply! <3
