### ISSUE TITLE
[FIXED] Playlists broken.

### ISSUE THREAD

**Issue by GrahamFinch** [YePpHa/YouTubeCenter#1440]
Whenever I go onto a playlist on YouTube, the playlists look disgusting in YTC and don't function the way they should.

Playlists should look like this on YouTube...
![good-playlist](https://cloud.githubusercontent.com/assets/8527284/6114755/219ef1a8-b055-11e4-93b6-035df87c059b.jpg)

When YTC is turned on, playlists look like this...
![bad-playlist](https://cloud.githubusercontent.com/assets/8527284/6114767/3a979822-b055-11e4-8de5-e27b8e071f36.jpg)

The arrow that I use to scroll through the videos isn't there, and those links towards the bottom (note the one I have highlighted) instead take me to a standard YouTube recommendations video rather than the videos that should be on the playlist.

I'm using version 2.1.7 of the Userscript.

**Comment by Zarggg** [comment]
This is a known bug with YTC. First, it is highly suggested to update to the current Developer Version of the addon; many changes have been made since 2.1.7 was released and it doesn't look like a new "stable" version will be released any time soon.

As a workaround for the bug, you can create the following custom style for the "youtube.com" domain in Stylish:

```css
.watch-playlist .main-content {
  height: 510px !important;
  overflow: auto !important;
}
```
This will force the playlist window to be visible for roughly the same height as YouTube's player. You can adjust the height as needed.

**Comment by GrahamFinch** [comment]
It worked! Thank you so much!

**Comment by KDsMax** [comment]
How on earth you managed to move playlist next to the video window?

**Comment by GrahamFinch** [comment]
...Isn't it always that way?

**Comment by KDsMax** [comment]
No, at least not with Dev version.

**Comment by ErdeFB** [comment]
Latest dev version on Chromium reporting in:
![Screenshot](http://i.imgur.com/4Q3oP2e.png)

**Comment by KDsMax** [comment]
Maybe your player size is different?

**Comment by KDsMax** [comment]
I still might have issues, this does not look right:

![image](https://cloud.githubusercontent.com/assets/10601224/6253360/635cac4c-b7a9-11e4-80e6-a04135286901.png)
