### ISSUE TITLE
Spacebar always focused on video

### ISSUE THREAD

**Issue by Lukas45** [YePpHa/YouTubeCenter#1546]
Whenever I press the Spacebar on a Video page, the spacebar will be focused on the video, causing it to play/pause. This makes me unable to type any comment that is more than one word, and no matter where I try to click, or focus, it always focuses on the video itself.

Or have I missed a setting somewhere?
Firefox 36.0.1 - Dev Version 492

**Comment by ErdeFB** [comment]
That's weird. Are you using the Flash or HTML5 player? Try switching to the other and see if it makes a difference.

**Comment by Lukas45** [comment]
It's set to Standard, but it also happens if I specifically set it to Flash/HTML5/Aggressive Flash

**Comment by Zarggg** [comment]
I'm having this issue as well on Firefox with the HTML5 player, as well.

It also only happens when I click the "Reply" link to post a comment. If I try to post a comment from the comment box above the comments display, the space bar works normally.

**Comment by Yonezpt** [comment]
YTC has a global shortcut option which allows users to use player shortcuts without having to directly click on the player. If this is the case with you then try disabling this feature which can can be found in YouTube Center Setting > Player > Shortcuts > Enable shortcuts on page

**Comment by ErdeFB** [comment]
I didn't recall having that issue when I had that enabled in Firefox some time ago. :/

**Comment by rayman89** [comment]
https://github.com/YePpHa/YouTubeCenter/wiki/Features#Enable_YouTube_Player_Shortcuts

**Comment by Lukas45** [comment]
Disabling YT Player Shortcuts did fix it, but seems like a weird turn-around for a fix.
It really shouldn't trigger the spacebar when selecting the Reply field (can say it doesn't happen in the normal comment box), as it really makes the function... bad

**Comment by Yonezpt** [comment]
YouTube might have changed something in their comment section which is causing this problem because this kind of issue was already account for by the author.

**Comment by Zarggg** [comment]
I suspect it was a recent change in YouTube. This only started happening a couple days ago.

**Comment by Eisys** [comment]
Yes, Youtube certainly did some sort of change to the comment area recently, because a theme I use doesn't work with it anymore, rest of YT is dark but the comment area is now white! So #BlameYT
But I am not seeing this issue however, if I comment or reply, space works as normal!

**Comment by Lukas45** [comment]
Well, so we can all say a change in YouTubes comment section is the cause of this, so wonderful. A workaround has been found until it gets fixes, so issue resolved :) Kinda

**Comment by Yonezpt** [comment]
It would be best to leave this open so that YePpHa can be informed of this issue and correct it.

**Comment by Lukas45** [comment]
Well good point

**Comment by YePpHa** [comment]
This is really weird, because the global shortcuts don't trigger when an input, textarea, object, embed or button is focused. Recently, YouTube have changed from using the iframe for comments to embedding comments directly in the page. This change might be what have caused this. However, the comment field is a textarea and therefore the global shortcuts should not trigger.

I will upload a new developer version which will have the iframe added to the ignore list, but it will probably not fix it.

**Comment by Trueffel** [comment]
ok, this is still an issue as it just started for me (41.0.2272.101 / dev build 495) No biggy for me tho as i dont need the shortcut function enabled.

**Comment by JaykeBird** [comment]
This issue just started occurring for me today.

I turned off "Extend shortcuts to page" and that fixed it. :) It's a fine enough work-around for me for now.

**Comment by harl** [comment]
FYI: Using dev build 497 - issue is still present (with "Enable shortcuts on page" checked)
Whenever the focus refers to an input field, YTC should just ignore the space bar, or loop it through. Same goes for the arrow keys.

**Comment by dastefster** [comment]
To add on to Harl's "FYI" I am also using devel. build 501 and having the issue if shortcuts on page is selected, also another weird thing.. not only does the space bar not work for commenting, it also won't allow me to type numbers haha

**Comment by DAOWAce** [comment]
Wow, this has been driving me insane for days.  Didn't even realize shortcuts worked on the page at all, never seen it until now.

I'm still on the stable build on both Chrome, Firefox and Palemoon.  Don't know why it started happening all of a sudden after Youtube's latest layout update ~2 weeks ago?  Only happens when typing in the comment REPLY section; typing out a brand new comment works just fine.

**Comment by BradJJ** [comment]
still having this problem in the latest dev build. using chrome.

**Comment by Inyokus** [comment]
@YePpHa
> This is really weird, because the global shortcuts don't trigger when an input, textarea, object, embed or button is focused. Recently, YouTube have changed from using the iframe for comments to embedding comments directly in the page.

This seems to be exactly where the problem is. I am now, too, experiencing this issue, and for me, the comment reply box isn't a textarea. It's a div with id "yt-commentbox-text" and "contenteditable=true". So all that should be neccessary, is to check if document.activeElement.isContentEditable is true. I have created a pull request with that fix.

**Comment by Yonezpt** [comment]
@Inyokus That will fail when users try to reply to other comments or edit theirs, or when YouTube decides to change the comment system again.

The best way is to do the way I suggested in https://github.com/YePpHa/YouTubeCenter/issues/1688#issuecomment-96109914 which is to check if the activeElement is inside the comment section.

**Comment by Inyokus** [comment]
It exactly doesn't fail then, when one is replying to a comment, since only then the comment box is in the YouTube page. The comment box on the the top is still in an iframe and isn't affected by this issue, even without this fix (but it would work, too, if they just copied the code they're currently embedding to the main page, since it's also a contentEditable div).

I don't get why this shouldn't work, when users try to edit their comments. The edit box is a contentEditable div with even the same class (just realized that I wrote id instead of class in my first comment).

That at least is the page as YouTube delivers it to me. It should hurt adding this fix, however, even if only few people have contentEditable divs instead of textareas in the comment area. I did, of course, test it, by the way. It does work.
