### ISSUE TITLE
Found a video with no HTML5 version or download options

### ISSUE THREAD

**Issue by mleyen** [YePpHa/YouTubeCenter#1548]
https://www.youtube.com/watch?v=_afzjFQXZho

Whatever is wrong with this video ? On Cyberfox 36.0 and latest developer build, this video will not load on HTML5 player, and thus, fall back to Flash player (also ignoring the Prevent autoplay option).
Plus, all download options are grayed out (and all other download addons such as Complete YouTube Saver fail to work).

**Comment by Zarggg** [comment]
It's a Vevo video. YouTube may still be doing special things with those videos that do not apply to their regular videos.

**Comment by Yonezpt** [comment]
It's not because it is a vevo video, it is because the video formats available are [protected streams](http://en.wikipedia.org/wiki/Protected_Streaming), making use of RTMPE protocol to provide the encrypted stream preventing even the most known online downloaders from creating a download link.

Since this technology can only be tunneled via flash it explains why YouTube switches to the flash player even in Chrome browser.

The only choices are to either search for an uncommon method of downloading this specific type of stream or find the same video hosted by someone else without the protection.

**Comment by Zarggg** [comment]
You have a point. I was under the impression that all videos grandfathered in from Vevo were subject to those restrictions, however.

**Comment by Yonezpt** [comment]
I am beginning to notice that more vevo videos are being converted to RTMP protocols, videos that I knew weren't previously protected (like 2 days ago) now became protected.

This is a strange move because this protection only works with Flash during a time when YouTube is trying to drop Flash and move to HTML5 permantently.

**Comment by emicom** [comment]
@mleyen
The yt link you provided is working on html5 in my browser (Pale Moon) just fine. I think it is the browser issue. Sometimes, not often though, the browser/YT switch on flash. Don't know why. Even on my own videos on YT I have the same problem - once on html5, rarely on flash. I think it can be https protocol - purely browser issue.

**Comment by Yonezpt** [comment]
Yes, now it is working fine and it can even be downloaded, but it wasn't before when OP first posted and it wasn't just a matter of being caused by protocol, the available streams were only playable via swf no matter what browser you used or protocol, now all the other formats are available. Strange, but if it is only a temporary situation then all the better.

**Comment by mleyen** [comment]
Can confirm, the Flash player seems to be gone for now. Maybe Google was doing some testing to see if it was viable.
