### ISSUE TITLE
#497  developer version not starting at all on Opera 12xx

### ISSUE THREAD

**Issue by raszpl** [YePpHa/YouTubeCenter#1625]
Win 8.1, opera 12.17
I was on developer $466 (or about that number), but decided to upgrade just now without backing up my previous version :(
#497 doesnt load, downgrading to 2.1.7 works again.

**Comment by raszpl** [comment]
just read https://github.com/YePpHa/YouTubeCenter/issues/1608
downgraded to #495 and its working again

**Comment by q1k** [comment]
Upgrade your browser

**Comment by danilaml** [comment]
@q1k not too start a browser flame but still there isn't competent replacement for good old Presto opera. Most browser are lacking basic features that opera has and also terrible at handling many tabs.

**Comment by Zarggg** [comment]
This really isn't the place to discuss what should or should not be considered a "basic feature," but Presto has not been updated in nearly three years.

It is ultimately up to the developer to decide whether old layout engines should be supported, but the general rule of thumb is to not expect support for browsers or engines no longer being developed. Opera has since moved to the Blink layout engine for its current version.

**Comment by TetraSky** [comment]
@danilaml You may want to give Vivaldi a try, then. While it's still early in development, it already feels like the Opera of old. Which is what Opera 15+ should've been had they not decided to ditch everything that made opera good, when they switched to chronium.

**Comment by danilaml** [comment]
@TetraSky Yeah, I've seen it and following closely it's development. It's still quite unstable and some Chromium inherited flaws (like poor tab/process memory/resources management) would never go away but it looks very promising. It's already implemented more than chropera since they decided to abandon Presto. I'll most likely switch to it when it matures and my 12 finally gives up.

**Comment by mikewinq** [comment]
Still not working in v.499. Opera 12.17 32bit Win7
