### ISSUE TITLE
Hide Video button not working

### ISSUE THREAD

**Issue by mwhprojects** [YePpHa/YouTubeCenter#1651]
I can't seem to click the icon on the top-right of video thumbnails to hide them in the subscriptions grid. Clicking it just goes to the video as if the button doesn't exist. Are there any options for this in the settings?

**Comment by Yonezpt** [comment]
For some reason the button is getting overlapped by the items below it, but we can't tell at first because the thumbnail is slightly transparent which gives the illusion that the button is over it and not under.

@YePpHa Setting `z-index: 1` to `.feed-item-container .menu-container` will fix the issue.

**Comment by GrahamFinch** [comment]
@Yonezpt Where do I insert that setting? I'm also having this issue.

**Comment by Yonezpt** [comment]
@GrahamFinch I am telling to the addon author which fix he can use, he will then insert it in the respective script line to achieve the desired effect.

**Comment by GrahamFinch** [comment]
@Yonezpt I just thought of something. If I put this code into Scriptish, would it work?

**Comment by Yonezpt** [comment]
Yes, it is scriptish's main purpose so you can do that until YePpHa has the time to implement the fix.
