### ISSUE TITLE
Center the video description

### ISSUE THREAD

**Issue by SnowGabe** [YePpHa/YouTubeCenter#1656]
It would be more aesthetically pleasing If I could center the video description. I'm fairly sure that isn't currently possible.

**Comment by Yonezpt** [comment]
Just to be clear, you are talking about centering the box below the video player that contains the video description and not about centering the text that is inside the description box, is that correct? If not then providing a visual example would be a good idea so that this can be easier to understand.

**Comment by SnowGabe** [comment]
I want to (horizontally) center the highlighted description box: http://i.imgur.com/7fu4OVe.png
The video is already in the middle.

**Comment by SnowGabe** [comment]
I had removed the recommended videos sidebar with uBlock.

**Comment by SnowGabe** [comment]
I had removed the recommended videos sidebar with uBlock.
