### ISSUE TITLE
Random black rectangle pushes video off center

### ISSUE THREAD

**Issue by Cyguard** [YePpHa/YouTubeCenter#1695]
exactly as the title says. does not happen with YTC disabled. using dev build 501.
![untitled](https://cloud.githubusercontent.com/assets/9603009/7383661/4bd86808-edd8-11e4-9e1a-d590b3a463a2.png)

**Comment by emm980** [comment]
True, youtube pushed new code / style for the layout and moved stuff out of place in conjuncture with YTC. It doesn't happen without YTC because that's the native placement, but when using YTC you want your layout, sizes etc on top of youtube's.

For my Stylish dark theme + all screen large player, I had to push div#player-api margin-left 427px and override .site-center-aligned #page margin-top by -9 px.

Either make your own stylish rules until YePpHa fixes the theme or don't use YTC.
If you need help on how to, say so.

**Comment by Yonezpt** [comment]
It's a recent YouTube style change, another change that makes no sense whatsoever. Instead of centering the video when in theater mode they are doing it via javascript, calculating how far from the left the player should be, add a 50% margin-left, subtract half of the player width and then it forces that distance onto the player style in the left attribute.

This one goes high up with the nonsense of the hardcoded player sizes that are constantly being polled every single timeshift while the video plays.

@YePpHa the following rule should fix the issue:

````css
.watch-stage-mode #player-api{
    left: initial !important;
    margin: 0 auto !important;
}
````

**Comment by Cyguard** [comment]
Its not really impacting video watching that much. more of a minor annoyance at best.

**Comment by Cephsus** [comment]
Yeah my YT player jump fare to the right side of the screen now (1080p). 

Using latest Dev version. Not familar with rules or codes, so ill wait for an update. ;)

**Comment by jakebailey** [comment]
Mine does nearly the opposite, adding the bar to the right while the video still stays centered.

![2015-04-28_21-42-01](https://cloud.githubusercontent.com/assets/5341706/7384016/9a54643e-edef-11e4-97a3-36d075d08918.png)

**Comment by TetraSky** [comment]
When the player size is 90% (1920x1200),  the video is hugging the right of the screen instead of being centered now, along with a large black bar on the right side that you can't see, it beingoffscreen. 80% shows the video somewhat centered though, looks exactly like the screen jakebailey posted.
![capture](https://cloud.githubusercontent.com/assets/7884915/7384034/7a9128ae-edf8-11e4-97a7-73c0f640ca66.JPG)

**Comment by aztectornado** [comment]
My particular offset box appears only in lights out mode, and is below the player. Seems to work fine with the lights on, but I'm having more issues with other things. (Details in #1696)

**Comment by TheCuza** [comment]
My bar is on the right side. I thought I could "fix" it by enabling dark background, but now that doesn't work anymore (not that I ever used it anyway before this).

**Comment by eduardog3000** [comment]
Not quite the same, but it is probably related: ![](http://i.imgur.com/5WgYuiQ.jpg) This is what I get with "Fit to Content".

**Comment by AtlasM** [comment]
While fiddling around with my own custom spaghetti code, I noticed that there was a second player added that was pushing everything around, div#placeholder-player.  I managed to fix my code by deleting that, and removing a new position:absolute property from the original api.  Since it's titled placeholder, the problem could go away on it's own.

**Comment by eduardog3000** [comment]
Well, this CSS seems to work as a temporary solution to my problem.

```CSS
#placeholder-player {
	margin: 255px auto 0;
    visibility: hidden;
}
```

**Comment by ButchDeLoria** [comment]
I'm also having a problem with Fullscreen Top Player mode, where when it's enabled the video will be replaced with just a black square filling the visible space in the tab. Firefox 37.0.2 if it helps.

**Comment by aztectornado** [comment]
@ButchDeLoria Same. Issue #1696 is where I listed mine.

**Comment by SINE** [comment]
Related
#1696
#1697

**Comment by sam288** [comment]
same problem for me (original thread #1703)
dev 501 + chrome
player set to fit to content

![untitled](https://cloud.githubusercontent.com/assets/10268922/7387994/24651c82-ee62-11e4-8c67-97c0b0f6d9a4.png)

**Comment by nikmurder** [comment]
exact same as above here confirmed
dev 501 as addon on FF 37.0.2

**Comment by SuperSajuuk** [comment]
Yep, happening here. (I eventually decided to just use the developer version as the stable version is now completely broken and no longer suitable: it should really just be pulled). Whenever I open the element inspector, the bar ends up on the left side, and switches back when closed.

**Comment by Eisys** [comment]
this needs to be fixed fast.. Really annoying!

**Comment by SINE** [comment]
Calm down, they noticed and will do that as fast as they can, it's a free project and they can't foresee YouTube's previously unannounced changes.

You could try learning JS and help fixing it, instead of saying "really annoying".

**Comment by Yrlish** [comment]
Using the latest dev, latest Chrome.

I have the new HTML5 player, black bar that discenters the player.
http://i.imgur.com/vEf5Ssu.jpg

**Comment by Yonezpt** [comment]
The issue has already been very well reported and duplicated plenty of times, please stop repeating it further and wait until the add-on author releases an update that fixes the problem.

**Comment by Yrlish** [comment]
@Yonezpt I know, therefore I wrote here and not in a new issue. ;)

**Comment by YePpHa** [comment]
I simply love YouTube so much /s

**Comment by Tailszefox** [comment]
Thanks for the quick fix, that solved the issue with the centering!

However, it seems the fullscreen top player is still broken. When enabled, it just displays a completely black page. Anyone else still having that issue, or have I updated incorrectly?

**Comment by Yonezpt** [comment]
@Tailszefox Please post in the specific issue thread that has already been opened for that issue. This thread was for a  random black rectangle pushes video off center, which has already been fixed.

Your issue belongs in the thread #1696

**Comment by Tailszefox** [comment]
Sorry, all those duplicates make things a tad confusing. Hard to say which issue is and isn't a duplicate and which issue is thus going to be taken into account. I figured it belonged here since the root cause seemed similar. Apparently not.

Anyway, thanks, I'll post in the appropriate thread.

**Comment by sam288** [comment]
Issue has re-surfaced
