### ISSUE TITLE
[Bug] Misaligned Player [Introduced Dev 503]

### ISSUE THREAD

**Issue by F43nd1r** [YePpHa/YouTubeCenter#1712]
I think the image is self-explaining: Player aligns so far left it isn't even fully in my screen
![unbenannt](https://cloud.githubusercontent.com/assets/10252708/7400736/5e95ffae-eebf-11e4-9782-c98a44ee41c3.PNG)

Firefox 37.0.2
Plugins should not interfere.

**Comment by One23** [comment]
I have this issue also, with latest 503 build on Firefox 38b9.  It only happens when in the 'Theatre mode', and with YTC setting 'Player' -> 'Player Size' -> 'Enable resize' disabled.  

Seems to be caused by commit bc9a2fcb7488a2e33a157c35752a2af9c7a29012, specifically the two CSS rules with '!important'.

**Comment by One23** [comment]
Confirmed fixed with 505 build.  Thank you!
