### ISSUE TITLE
16:9 player aspect ratio with 1080p player size isn't actually 1080p size

### ISSUE THREAD

**Issue by CathalCraft** [YePpHa/YouTubeCenter#1716]
I have the player aspect ratio set to 16:9 and the player size to 1080p, but the size of the video isn't 1080p. The video has black bars added to the side which reduces the video size below 1080p. I included a screenshot for an example.

A way to fix this would be to extend the player vertically with the 16:9 aspect ratio so the video properly stretches to be 1080p.

Example: http://puu.sh/hvF2y/6250defbe1.jpg
Settings: http://puu.sh/hvF4t/bed57f4d0b.png

**Comment by Yonezpt** [comment]
It is 16:9, the issue lies with the control bar visibility or player height. If the control bar is set to auto-hide as I suspect it should then the video would fit correctly to the rest of the player frame, or if the control bar isn't set to auto hide then the player should have an extra 30px added to it's total height to accomodate that bar outside the 16:9 frame.

It's strange that this is happening because it wasn't an issue before.

**Comment by CathalCraft** [comment]
I tried setting the control bar to autohide and it still had black bars on the sides.

**Comment by Yonezpt** [comment]
Might be because you configured the sizes incorrectly, do they still appear if you reset the YTC options to default?

**Comment by CathalCraft** [comment]
I think it should be noted that this happens on Firefox with Flash. The issue doesn't occur on Chrome with HTML5.

I want to use Firefox with Flash because Chrome is super laggy with 4k videos.

**Comment by Yonezpt** [comment]
Oh so that might explain it. YTC is trying to compensate the player height to account for the control bar, which works correctly with HTML5, but the same doesn't work for the Flash player because it resizes differently.

**Comment by CathalCraft** [comment]
I reset my settings and the problem is gone. I'll go redo all my settings again and report back if the issue pops back up.
