### ISSUE TITLE
Scroll-to-player broken again

### ISSUE THREAD

**Issue by Kanegasi** [YePpHa/YouTubeCenter#1766]
There are two options: individual player size options and a main one under layout that's hidden if static header is disabled.

The scroll-to-player in the player size options has always been broken, scrolling not to the player, but past it about the same pixel height as the header. Sometime in the last few dev versions, the working option under layout has stopped scrolling altogether.

Resetting options does not fix.

**Comment by LaVey-Charkus-Veros** [comment]
Yeah, I also noticed that immediately. Strangely enough, now the one in the individual player worked for me, although I had to deactivate both the static header and scroll to player options from the General >> Layout tab.

**Comment by Kanegasi** [comment]
It just occurred to me that I could be a little more specific about how the scroll options currently work.

[All options off](http://i.imgur.com/a0ero8d.png)
[Scroll option under static header](http://i.imgur.com/GOxxn80.png)
[Fill size with scroll option (static off)](http://i.imgur.com/ldiKibI.png)
[Fill size with scroll option (static on)](http://i.imgur.com/dfnhRnd.png)
[Fill size with scroll option (static and scroll on)](http://i.imgur.com/dfnhRnd.png)

**Comment by CameronJRoss** [comment]
I'm having this issue too, so I did a little investigation and this regression happened because of the fix for #1723 in build 514 (commit bf177e75bb3135fc17243ac9591ead8e679f6c7c).  By commenting out `ytcenter.utils.scrollTop(0);` on line 20957 it fixes the issue for me.  I'm not sure what the proper fix is, but I can say that the function `whyDoYouScrollDotCOM` doesn't make a lot of sense and should be refactored.

**Comment by YePpHa** [comment]
@CameronJRoss the function `whyDoYouScrollDotCOM` is made because YouTube sometimes scrolls down the page. It has something to do with hiding the header. I will just have to make a condition that checks if `Scroll to player` is enabled and if it is then disable that part.

**Comment by Kanegasi** [comment]
I have noticed that YouTube scrolls a bit down on it's own, but only on channels. It can be frustrating trying to click "videos" on a main channel page only for the page to scroll down a bit once loading was finished, causing me to click the promoted channel video instead. Also, when I get to the list of videos, I could end up clicking a video when I was trying to click the "popular/uploaded time" dropdown.

**Comment by Yonezpt** [comment]
@YePpHa If you change the ID of `#masthead-positioner` to something different then the `www-pageframe` script won't be able to scroll the page due to the bar offset anymore. Just remember to clone its style properties to the new ID you give it, they are located in the `www-pageframe-XXXX.css` file.

**Comment by YePpHa** [comment]
@Yonezpt I will look into it. It would be great if we wouldn't have to account for YouTube scrolling the page.

**Comment by Yonezpt** [comment]
Will certainly fix quite a few bugs. In case of being helpful, this is the function responsible for that header auto-scrolling when a page finishes loading, located in `www-pageframe.js`:

````javascript
function Gl() {
    if (Al = R('masthead-appbar')) {
        Bl = R('masthead-positioner');
        Cl = R('masthead-positioner-height-offset');
        xj();
        Hl();
        Il();
        Jl = new lk(Kl);
        var a = Ll;
        r('yt.scheduler.instance') && (a = function () {
            ah(Ll)
        });
        Ml.push(N('init', a));
        Ml.push(N('dispose', Nl));
        Ol = wj();
        vh.getInstance();
        Pl(Ah(0, 128) ? Ah(0, 129)  : !0);
        Ql = qd('html', void 0, void 0) [0];
        Ml.push(N('masthead-ticker-close', Rl));
        Ml.push(N('appbar-guide-delay-load', Hl));
        Ml.push(N('page-resize', Sl));
        El || Ll()
    }
}
````

**Comment by YePpHa** [comment]
@Yonezpt I found that the `#masthead-positioner` element is only a container and I can move the elements inside it instead of itself. This makes YouTube's function return `-0` instead of `-51` and it looks the same without any side effects (what I've observed).

So I've changed:
```CSS
body.hide-header #masthead-positioner {
  top: -51px;
}
```
to
```CSS
body.hide-header #masthead-positioner > * {
  margin-top: -51px;
}
```

The animation part I'm using has also been changed the exact same way. I'm using `margin-top` as the children of `#masthead-positioner` do not have the `top` property set, which breaks the animation, and this was the simplest way. I could use `top` by setting a default top CSS property for the children.
