### ISSUE TITLE
Rating Bar doesn't work

### ISSUE THREAD

**Issue by gopego** [YePpHa/YouTubeCenter#1817]
well since 2 last updates the rating bar doesn't work anymore, it's not like a really big deal, but it would be better if it works like it suppose to do. Thank you

**Comment by Zarggg** [comment]
Make sure you have enabled API v3 on the General settings page.

**Comment by SINE** [comment]
v3 API doesn't fix it, because the problem is caused due to the API-Key that YouTubeCenter is using being a free one and it's completely overloaded (too many YouTubeCenter users).

A little info from the YouTubeCenter main developer: https://github.com/YePpHa/YouTubeCenter/issues/1783

You can fix it by using your own API Key, to do that click on the little question mark next to the "API Key" field in the YouTubeCenter settings and then following all steps (you need a Google Account for that).

Related issue:
#1814


Related issues:

**Comment by RegDenied** [comment]
I created my own Key and it now shows the available quality in the thumbnail, but the rating count and the rating bar are still missing. 
These are the errors I got in the firefox console: http://imgur.com/L4Rr1QL
Thx

**Comment by SINE** [comment]
@RegDenied Please reset your YoutubeCenter Settings under Settings>General>Reset settings (on the bottom).
Then uninstall YouTubeCenter.
Restart your browser and re-install the Greasemonkey Script.

**Comment by RegDenied** [comment]
@SINE That did it. Thanks a lot!

**Comment by gopego** [comment]
@Zarggg Thx, it works fine now
