### ISSUE TITLE
YouTube center FF XPI crashes firefox with E10S

### ISSUE THREAD

**Issue by jackwickham** [YePpHa/YouTubeCenter#1824]
With the upcoming change to use E10S (multiprocess firefox), the XPI version of youtube center breaks, crashing the entire web process (all tabs). E10S is now approaching release because it has been enabled in the developer edition builds, not just nightly as of FF40.0a2 (released yesterday). According to the [mozilla wiki](https://wiki.mozilla.org/Electrolysis), it may reach release as early as FF42 (coming in 6 months).

[MDN article on making addons compatible](https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox)

**Comment by Yonezpt** [comment]
This shouldn't be happening because YePpHa already updated his software to be compatible with E10 back in [Nov. 30th, 2014](https://github.com/YePpHa/YouTubeCenter/issues/1212).

I just tested the latest Dev version in the latest Nightly 41.0a1 (2015-05-18) and it crashed 0 times, I suspect you might have another add-on conflicting with YTC. If you have anything else installed then uninstall them all, restart Nightly and see if it keeps crashing. I suggest uninstall because just disabling add-ons doesn't seem to work the way it did before E10 was introduced.

**Comment by EchoDev** [comment]
The YTC extension on addons.mozilla.org is a very outdated version. Using the dev version will not make it crash. 

The addons.mozilla.org version should be updated or removed before E10S officially comes out (These kinds of crashes might taint the YTC name forever.)
