### ISSUE TITLE
How can I totaly uninstall youtubeCenter in firefox? there is a problem

### ISSUE THREAD

**Issue by aviadhhh** [YePpHa/YouTubeCenter#1878]
After I removed the addon from firefox it still shows the page with no comments and with no suggestion (videos). also I clean all the history. screenshot attached. 
http://i.imgur.com/O6UXgOI.png

**Comment by Yonezpt** [comment]
If you are not the same user as this one which reported the exact same YouTube problem: http://www.reddit.com/r/youtube/comments/38rl3k/why_cant_i_view_comments_or_related_videos/

Then I suggest you also try what worked for him. If YTC has been removed then another add-on is causing that issue, I also am not aware of any YTC feature that can remove suggested videos so that's a big hint on this not being caused by YTC in any way.

**Comment by aviadhhh** [comment]
Thank you for your answer. uBlock case the problem.

**Comment by Zarggg** [comment]
@aviadhhh: Please close this issue as it is not related to YTC.
