### ISSUE TITLE
When is a update coming there none for a while

### ISSUE THREAD

**Issue by audjack99aus8** [YePpHa/YouTubeCenter#1910]
When is a new version coming out please?  There has been no updates for quite a while now.

**Comment by Piter432** [comment]
When @YePpHa will able to focus on his userscript/extension.

**Comment by KamranMackey** [comment]
@audjack99aus8 He's either taking a vacation or finishing up his exams. He'll be back soon.

**Comment by SnowGabe** [comment]
There should be more contributors.

**Comment by Piter432** [comment]
@SnowGabe Yeah, but this userscirpt/extension has many lines both in source files and compiled files and @YePpHa annouced that he is trying to change build system from Ant to Grunt, which requiers Node.js (see #1025).

**Comment by SuperSajuuk** [comment]
@SnowGabe I agree. Or maybe there needs to be more community involvement, instead of everyone shying away from contributing code fixes for people to test on the basis that "it's YePpHa's script, I'm not touching it". 

There's nothing wrong with someone contributing a code fix, getting people to update and getting feedback from the community on said fix: every time something breaks for everyone (whether it's YouTube or an issue in the script), there's usually a swarm of people posting here, so it shows this script has a large community who are clearly willing to report problems.

Just a shame they don't get fixed until YePpHa sees it. It's kinda disappointing to be honest.

**Comment by Yonezpt** [comment]
Even if I decided to fix a few of the problems, the system is built with Ant and it has quite a few dependencies (especially the ones that require the version number to increase whenever a new version comes out), these are batch files/task runners that I do not possess and modifying the code without accounting for all of these necessary changes might create serious problems for further updates from the author.

What I might try to do once I have some free time is to suggest the fixes for the users directly in their threads, but these will only work best for the userscript versions since those can be easily changed by even amateur users.

**Comment by SuperSajuuk** [comment]
@Yonezpt Ah, didn't realise Ant building is the reason why nobody can contribute. Definitely need a brand new distribution system to allow more contributions.

**Comment by bottleblue** [comment]
I've been using another script, Youtube+, until this one gets fixed. It seems to be constantly updated. It doesn't have nearly as many options as YTC (you can only set one custom resolution) but it works well and it even shows the screenshot for the video if you're using HTML5 which YTC never did for some reason. Hope it's ok to post the link, if not just search for it on greasyfork  https://greasyfork.org/en/scripts/9932-youtube

**Comment by rdamiano** [comment]
Yeah, using Youtube+ as well for now. The memory leak from YTC is really bad.

If Youtube+ just had thumbnail previews and started loading the video as soon as I went to the video page (vs me having to click play, wait, then pause when it starts buffering) it'd be perfect.

**Comment by bottleblue** [comment]
You can use a separate script for thumbnail previews https://greasyfork.org/en/scripts/2818-youtube-animated-thumbnails-preview-videos   that's what i use. Can't help you with the autoplay or buffering. There might be scripts to do that but I prefer my vids to not autoload or buffer.

**Comment by rdamiano** [comment]
I've seen that, and I've seen other addons for it, too. But for some reason all of them only cycle through three screenshots, which is better than nothing, but I've been spoiled by YTC since it seemed to generate countless screenshots - not sure how YTC does it though,

**Comment by bottleblue** [comment]
hmm I didn't realize that YTC did that. It really is the best script ever! :D

**Comment by SuperSajuuk** [comment]
@YePpHa posted an update today (30 mins ago as of this post), but I haven't a clue what it changed. Can you give us a changelog of what was fixed please?

**Comment by jasontibbitts** [comment]
You're already on github; why not just look at the commit list?  I see one change: 

Removed option to disable v3 API. Switched to use v3 API for detecting country for channels (haven't seen it accessible with v3 API yet even with it described in the API overview). Fixed issue with grid view.

**Comment by SuperSajuuk** [comment]
@jasontibbitts I'm not familiar with github and the commit history is mostly suppressed, which tells me nothing at all. The only edits not suppressed are just 525 -> 526 in various main files: one section just tells me that a bunch of files were deleted/edited, and another is suppressed and I can't load it due to tampermonkey.

So a full changelog would be helpful for people who either can't read the commit history, or don't understand the code repository.

**Comment by ErdeFB** [comment]
People who are not familiar with github functions besides the issue reporting system should not concern themselves with such details unless trying to learn said systems. When a issue gets fixed, the author of the ad-on usually closes the issue report informing of a fix.

**Comment by SuperSajuuk** [comment]
@ErdeFB That's a pretty interesting statement to make. Just because I don't understand anything beyond the issue tracker doesn't mean I have no right to enquire about a list of changes made between versions. Considering the length of time between 525 and 526, I feel it's important to know what was changed.

**Comment by ErdeFB** [comment]
@SuperSajuuk  I didn't say you had no right to enquirer. However, it is rather selfish as the information is already provided and you are asking for people to do extra work for your sake since you can't be bothered to figure out how the already standing system works which has the information you asked for.

Every single change is listed in the commit list. Also, if you want to keep up what is fixed and not you can opt to watch the repository as like I stated earlier, the author closes fixed issue reports.

Anyways, this is a issue tracker, not a discussion forum so please keep opinion pieces and unrelated banter to a minimum, please. I keep receiving email notifications for your off-topic comments which I do not appreciate and I bet not that many other people either.

If you have demands to the author or want to give him feedback, you can find his contact information in his Github profile.

Thanks.

**Comment by SuperSajuuk** [comment]
@ErdeFB I must have missed the section where it says your a moderator of the tracker. If you don't want email notifications, unsubscribe from the thread instead of complaining. It's certainly not really your place to determine what the issue tracker is for, as this is the only method of communicating with users of the script in a suitable method.

**Comment by rdamiano** [comment]
http://i.imgur.com/55GXL1H.gif

**Comment by Yonezpt** [comment]
@SuperSajuuk When YePpHa publishes a new version you can follow its changes by going to his profile page (https://github.com/YePpHa), click on the "Public activity" tab (https://github.com/YePpHa?tab=activity) and you can see a short resume of the changes he made under every "Pushed to master" activity. Clicking on the weird number behind the changes will lead you to an extended list of changes, if there is more.

Of course this depends on him writing the changes he makes, if he doesn't write then the only way to see what changed is to see the code changes directly, which requires more advanced knowledge to understand.

**Comment by Inyokus** [comment]
@Yonezpt @SuperSajuuk That exact same information is also available in the [commit history](https://github.com/YePpHa/YouTubeCenter/commits/master), except that this will only show changes to YouTubeCenter and not other projects YePpHa may contribute to. You can expand descriptions there by clicking on the button with three dots next to the shortened one.

**Comment by SuperSajuuk** [comment]
@Yonezpt Exactly my point, if he doesn't write much of a description, then it's impossible know the full change logs. As this is a developer version, I would have assumed (wrongly it seems) that @YePpHa would have wanted to let us know of every change between versions, so that we can find out quickly if a bug is fixed in the tracker.

**Comment by Betsy25** [comment]
It is no longer fixable, what point does it make to give some name to a couple of tries ?

**Comment by Yonezpt** [comment]
@Betsy25 What do you mean? It is working for me, apart from some features that need to be updated and YePpHa is still working on the software: https://github.com/YePpHa?tab=activity

I think this thread has already been answered, there is no point deviating from the original question.

**Comment by Inyokus** [comment]
@SuperSajuuk I don't read the code diffs very often, but usually YePpha does mention all changes in the commit message. Also, when an issue is fixed, the description contains something like "Fixed #IssueNo", which also automatically closes the issue in the tracker. This should, if I understand you correctly, be all information you want.

**Comment by ErdeFB** [comment]
Closing this issue report as it is not really relevant to the development of the script. The author updates the script when time allows it.

For anyone wanting to find out what exactly changes per new version, you'll find plenty of advice how to do that above.
