### ISSUE TITLE
DEV builds = Developer version ?

### ISSUE THREAD

**Issue by ireun** [YePpHa/YouTubeCenter#1938]
Hey, I'm currently doing a bit of cleaning up in the wiki, and i'm in a small trouble, in the "[Developer version](https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version)" page you can find a change log of.. v2.1.7.. Isn't it the stable build? 

Well, v2.1..7 isn't even tagged here on github, I even think it isn't even present as a commit, as i cannot find it. Here https://github.com/YePpHa/YouTubeCenter/commit/00afa635611b814ed5179769d1d0ca9930fec056 you can find an iteration to v2.1.6 and i couldn't find anything higher than that..

I want to post there some kind of an info about DEV builds, these ones that are in the /dist/ folder.

@YePpHa, @Yonezpt, @KamranMackey is it the same thing, the wiki is outdated or maybe Developer = beta, while DEV = nightly?

**EDIT:** I think i got it, it's a changelog from 2.1.7, though it outdated as hell, so i think a better way would be to add a link to commits, as it will be always current that way.

**Comment by Zarggg** [comment]
The link you posted for 2.1.6 does not resolve because you replaced the subdirectory "commit" with "issues." Here is the proper link: https://github.com/YePpHa/YouTubeCenter/commit/00afa635611b814ed5179769d1d0ca9930fec056

From what I've noticed, it seems like the [changelog](https://github.com/YePpHa/YouTubeCenter/wiki/Changelog) on the wiki only includes the releases up until 2.1.7, after which point *all* changes have been done in dev builds (named "Developer Versions" here, but IMHO they basically serve the same function as alpha/beta builds). I remember @YePpHa saying something along the line that the commit log serves the same purpose as a changelog for the Developer Versions. I agree with you that these should be tallied and summarized if/when an official "stable" build is released.

As far as I can tell, the files inside the /dist/ directory are the current Developer Version packed for browser installation -- "dist" being short for "distribution."

**Comment by Yonezpt** [comment]
The change log is for 2.1.7 and also to differentiate it from the developer version as well. If you follow the [reddit link](http://www.reddit.com/r/YouTubeCenter/comments/2wcyfg/youtube_center_developer_version/) you can read what is new in 2.1.7 as well as **what is in the developer version, but not in the stable version**. Read `Added features not in v2.1.7`.

This is to let users know of new features thare are being currently tested in the developer version if anyone wants to try them out before shipping to stable. At least this is what I have concluded.

You won't find the 2.1.7 commit because it is probably not present on the GitHub commit, they are instead located on the GitHub page repo (http://yeppha.github.io/). In the repo we currently are, there is only the dev version, as far as I could tell. But to be sure, wait for YePpHa's input on this, he knows this better than anyone.

**Comment by ireun** [comment]
@Zarggg Yup, but it's Github that messed up that link, fixed. ;) The summarized DEV changelog that you can find [here](https://www.reddit.com/r/YouTubeCenter/comments/2wcyfg/youtube_center_developer_version/) was mentioned in #1474.

@Yonezpt Right, I've added small info in the wiki about this, also i think you may be right, v2.1.1 that is tagged doesn't have version iteration in the code, only build number is higher.

Let me know what do you think (Developer version and main page in the wiki.)

Thank you! :)
