### ISSUE TITLE
Disabled Dash Playback 360p only

### ISSUE THREAD

**Issue by dunnodun** [YePpHa/YouTubeCenter#2054]
I read that 480 and 1080p arren't able to be played without dash playback but 720p doesn't show up as well if it's disabled. 
Currently I only have the 360p option in all videos I've played with disabled dash playback, making that option in the most cases useless.
Edit: This is only the case with Firefox as browser.

**Comment by LevyWilson** [comment]
I'm experiencing this as well, which is weird. I remember having the 720p option before I reinstalled my browser. I had cleared by profile settings and installed Pale Moon 64 bit about a week or so ago. Could having a 64 bit Firefox install be the cause? Or did Google finally drop support for non-dash playback in 720p?

**Comment by Zarggg** [comment]
I tested a couple random videos and did not experience this problem. This could be an issue in your specific browser environment.

Moonchild recently made the decisions to give Pale Moon a separate GUID from Firefox and to not support Australis. I don't think that directly impacts YTC, but it might if you are using the Firefox add-on release (as opposed the userscript release). I don't believe that @YePpHa is specifically supporting Pale Moon.

Also keep in mind that 64-bit versions of Firefox may have unresolved issues with browser plugins. I do not know if this impacts HTML5 or Flash at this time, but it does impact Silverlight (just as an example; YouTube does not use Silverlight).

**Comment by LevyWilson** [comment]
Switched back to 32 bit, didn't work. Used Greasemonkey and the Firefox Add-on version, no change. This is making me regret deleting my old profile. But I needed to. It was a mess and I couldn't delete old browser history without the browser locking up. Guess I'll just live with 360p for now and turn DASH on when I want to watch 720p videos. But the reason I had DASH off to begin with was because my ISP sucks and I need it to buffer...

**Comment by dunnodun** [comment]
Ok the problem is Firefox-specific and has nothing to do with YouTubeCenter. 

Those preferences have to be activated in Firefox. You can check it [here](https://www.youtube.com/html5). 
media.mediasource.enabled;true
media.mediasource.webm.enabled;true
media.fragmented-mp4.ffmpeg.enabled;true
media.fragmented-mp4.exposed;true

With this you should be able to use YouTubeCenter without dash playback in 720p on Firefox.

**Comment by LevyWilson** [comment]
Didn't fix it.

**Comment by dunnodun** [comment]
Are you sure that you see this? ![html5](http://i.imgur.com/ek8vZmW.png)
Are you using the standard version or the developer? I'm using since about 1 year only the developer version, because the standard was always very buggy for me. 
I would recommend that you reset your Firefox profile and try it again with the standard version and if the problem still persists, give it a try with the developer version. 

For me it works flawlessly now, I can watch 360p and 720p in Firefox without DASH playback being active.

**Comment by LevyWilson** [comment]
Okay, I checked again and I guess when I went to reinstall Pale Moon the second time, I had installed the 64 bit version instead of the 32 bit one. I reinstalled with the 32 bit version, installed Greasemonkey and installed the developer version of YTC. I get the 720p for DASH playback off now. It might just be an incompatibility with Palemoon 64 bit. Or I just got lucky with this reinstall. I dunno. I'm gonna set my browser back up again anyway. Take care.

![2015-10-04 11_41_36-some thoughts on pretending and honesty - pale moon](https://cloud.githubusercontent.com/assets/10651328/10268646/f1042ea8-6a8c-11e5-8869-52265b68e791.png)
![2015-10-04 11_42_26-youtube - pale moon](https://cloud.githubusercontent.com/assets/10651328/10268651/15dfbb52-6a8d-11e5-9403-6ac1b4d3e0d3.png)

**Comment by Zarggg** [comment]
Keep in mind that Pale Moon is not Firefox; it's a fork of an older version of Firefox that is developed independently.

Firefox's MSE compatibility was initially designed to work specifically for YouTube (with more general compatibility coming down the line). Unless the Pale Moon development team has ported Firefox's MSE functions to Pale Moon, it is likely that Pale Moon's support for MSE may be different, incomplete, or possibly non-existent.

Does the HTML5 player/MSE work properly with YTC disabled?

**Comment by LevyWilson** [comment]
Yup. The HTML5 player works fine with YTC turned off.

**Comment by Zarggg** [comment]
Then to me it sounds like YTC is definitely mucking up something specific to Pale Moon. I'm out of ideas to try right now; we may have to wait on @YePpHa to track this down.
