### ISSUE TITLE
dev build in greasemonkey

### ISSUE THREAD

**Issue by jcpro** [YePpHa/YouTubeCenter#2160]
How do I install the dev build of YTC in greasemonkey as my use of this tool is affected by the FFv43 code signing issue.
The version on the greasemonkey site is 2.1.7: https://greasyfork.org/en/scripts/943-youtube-center

**Comment by Pazns** [comment]
Just go there : https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version
and pick " Userscript: YouTubeCenter.user.js ".

**Comment by jcpro** [comment]
The dev build installs but doesn't appear to work as I can't use the download function to download a video or convert to MP3, is there a support forum for Greasemonkey addons?

**Comment by Pazns** [comment]
@jcpro :
> is there a support forum for Greasemonkey addons?

It's here.

For the download function, it works perfectly for me, then the problem is probably on your end.

If you don't have time to debug your installation, you can try other ways, maybe more reliable than YoutubeCenter for which it is not the primary function at all.
Try Youtube-dl [https://rg3.github.io/youtube-dl/], a powerful yet very easy to use command-line executable.

**Comment by jcpro** [comment]
That tools works quite nicely, thanks for linking it.  That's pretty much all I use YTC for anyway.
