### ISSUE TITLE
Dev version no longer supported in Chrome

### ISSUE THREAD

**Issue by YoderofKansas** [YePpHa/YouTubeCenter#2188]
Can't use the dev version in chrome anymore.  Chrome automatically disables extensions that are not found in the chome web store.

**Comment by Yonezpt** [comment]
It has been like this for quite some time, use the [userscript version](https://github.com/YePpHa/YouTubeCenter/raw/master/dist/YouTubeCenter.user.js) with the Tampermonkey extension instead.

**Comment by Nxt3** [comment]
You can't. Chrome won't let me add it. I have to open the Extensions page in Chrome and then drag the .js file and install it like that. Every time I restart my computer or update Chrome--I have to go through the process all over again.

**Comment by ErdeFB** [comment]
And you are sure you tried to add it normally with tapermonkey?

**Comment by Yonezpt** [comment]
@Nxt3 I clearly said "with the Tampermonkey extension", this userscript is not meant to be loaded by Chrome directly.

**Comment by Nxt3** [comment]
@Yonezpt I have the Tapermonkey extension. If I click on the userscript found on GitHub--it opens up Tapermonkey but you won't be able to install the script.

**Comment by Nxt3** [comment]
![tapermonkey_fail](https://cloud.githubusercontent.com/assets/2940826/13688548/aafd111e-e6f0-11e5-9f81-40922c32a348.gif)

**Comment by Yonezpt** [comment]
I can install it just fine on Chrome 49.0.2623.75 with Tampermonkey on default settings by following exactly the same steps as in your example, it just takes a bit to load the script into Tampermonkey. It is after all almost 30.000 lines of code, it is not a small userscript by any means. If it still doesn't work as it should, try with a new Chrome profile and default Tampermonkey settings since you could have changed something that is preventing it from installing correctly.

**Comment by Nxt3** [comment]
Ha. Waiting longer let me install it no issues. I feel so stupid. Thanks
