### ISSUE TITLE
Pretty broken on mozilla-central by now

### ISSUE THREAD

**Issue by mzso** [YePpHa/YouTubeCenter#2321]
Disabling annotations doesn't work, disabling autoplay doesn't work. At least setting quality still works.

**Comment by mzso** [comment]
So. You just decided to close it without reason or explanation.

**Comment by ErdeFB** [comment]
Because it is in a essence duplicate of at least #2293 and #2324 something that would have been trivial to find out and since you are a long time user of this issue tracker you should know how to do so.

This is the last time I explain myself to you since you have failed to do your due diligence several times (checking for duplicates) when opening new issues and your behavior has been problematic even before that. 

I don't like wasting my time so that is why I closed your last two opened issues. This one shouldn't even have deserved any kind of reply since it is just a rant in form of an issue report.

**Comment by mzso** [comment]
Neither of those are about disabling annotations or autoplay. Much less named as such.
How do you imagine one finding such "duplicates"?

Just a hint: Decent people close duplicates with a note of the duped issue.

**Comment by ErdeFB** [comment]
Decent people also create one issue per you know, issue. Yours is mostly a rant of how the addon is completely broken. We already have one of those open issues with more insight like this one #2324. It's not as old as yours, but it clears up some things and is the first issue on the open issues page. 

There is no reason to close an issue with reference to other issues when it is clearly faulty and has no worth since that creates reference clutter.

But since I'm a nice guy I'll humor you this time (won't link directly, but you should figure out how to open them).
Here is at least one for annotation: 2278 
And here is one for the auto-play: 1869
And if you had actually searched, you'd find that both issues have several reports.
You're welcome.

**Comment by mzso** [comment]
Those are too old to be relevant. (especially the older one) Anyway, I give up. It's pointless dealing with you if yeppha's not around.

**Comment by ErdeFB** [comment]
Incorrect. The oldest one which still applies is always the most relevant one. It's a shame you do not know this considering you seem fit to school me about how issue trackers work.

From now on, expect no replies when you try to call me out in the future since as was proven I'm more suited for this than you are.

**Comment by mzso** [comment]
(Since it both broke some weeks before, I doubt that you're right.)
