### ISSUE TITLE
Firefox 57 (Firefox Quantum) compatability?

### ISSUE THREAD

**Issue by Njs10** [YePpHa/YouTubeCenter#2454]
With Firefox 57, also known as Firefox Quantum, being release on November 14th, having a beta out for people to try out it mentions some extensions being labeled "Legacy Extensions" and thus are rendered unusable until updated, From what I have it labels stuff like Stylish, Greasemonkey and Youtube Center as legacy extensions. Greasemonkey has confirmed they are updating, Stylish has a fan remake named Stylus, so all that's missing is Youtube Center which currently doesn't work. Any news if we're getting this Firefox 57 support?

**Comment by rekd0514** [comment]
Did we find a manual way to install Youtube Center developer into greasemonkey yet?

**Comment by MegaScience** [comment]
Greasemonkey is now under similar restrictions Tampermonkey has been under, so updating wouldn't be a simple task. I have a few hand-made userscripts for YouTube that stopped working since Greasemonkey no longer has access both to itself and the page-space window properties. I have to either inject my code into the page and forego Greasemonkey's built-ins and such, or be unable to touch the required elements while I stay within Greasemonkey for those built-ins. I'm not sure this could survive as a userscript in this state, but a standalone WebExtensions add-on... maybe.

**Comment by YePpHa** [comment]
I will not add support for Firefox Quantum for YouTube Center. However, [YouTube Center's successor](https://github.com/YePpHa/maia-yt) will get support for it.
