### ISSUE TITLE
Add "tags" in description boxes

### ISSUE THREAD

**Issue by SWFlash** [YePpHa/YouTubeCenter#33]
On each YouTube video, in the source code you can see the tags being listed inside a "meta keywords" HTML tag. These tags used to be listed after the description in the old layout, but after the update they were removed from there. Can you add them back in their place?
![image](https://f.cloud.github.com/assets/5409286/1102469/a1293e6e-1822-11e3-98a6-8298bdae42c9.png)

**Comment by ireun** [comment]
@YePpHa Almost two years later... ;)

**Comment by SuperSajuuk** [comment]
@ireun I'm pretty sure this was already added, at least because I can see the tags when YT Center is loaded ;)

My guess is that @YePpHa fails to add commit messages that reference tickets on a regular basis, hence why it's impossible to know when a feature/bug ticket is actually implemented into the code.

**Comment by ireun** [comment]
Well, You are right, I've not noticed it before.. Or maybe i forgot about it, anyway, closing this one. :)
