### ISSUE TITLE
Custom thumbnail upload fails (Firefox)

### ISSUE THREAD

**Issue by Anachon** [YePpHa/YouTubeCenter#666]
When uploading a selfmade thumbnail for my videos it stops after a while with a little white exclamation mark in a blank space, mouse tooltip says "Default Error".

I'm using Build 351 with Firefox v30 on Win7, disabling YTC addon solved the problem so it should be a bug in the recent build(s).

Sry 4 bad english if present.

**Comment by ExcalibursZone** [comment]
Sorry for the necro, but this issue still is not fixed in latest dev build 495. Uploading a custom thumbnail fails 100% of the time with Firefox 36.0.3 on Windows 8.1. I have no idea why it isn't working. I have to disable YTC then upload. Far too many clicks for such a simple thing that YouTube does by default without issues. Why would an upload script be messed with by YTC?

**Comment by ErdeFB** [comment]
Works fine with the latest Chromium (at the time of writing) and latest YTC dev build.
Can other Firefox users verify? Or other browser users?

**Comment by cornandbeans** [comment]
Can confirm this problem still exists in Firefox. Have been using Dev build since few years ago.

**Comment by ireun** [comment]
Merging issues regarding this to one github issue: Check out issue number "1932".
